[package]
name = "basecamp"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
alexandria_math = '0.5.0'

[dev-dependencies]
cairo_test = "2.11.4"
